### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by digitaldomino-coder** [TheKye/EM-Framework#40]
**Describe the bug**

**To Reproduce**
1. Start up a 10.1 server
2. Install EM framework
3. Launch  Eco

**Expected behavior**
Server launches

I get this error.

Failed to start the server. Exception was Exception: MissingMethodException
Message:Method not found: 'Void Eco.Gameplay.Interactions.Interactors.InteractionAttribute..ctor(Eco.Shared.SharedTypes.InteractionTrigger, System.String, Eco.Shared.SharedTypes.InteractionModifier, System.String[], Single, Single, Eco.Shared.Items.ClientPredictedBlockAction, Int32, Boolean, Eco.Shared.Items.TriBool, System.String, Eco.Shared.Items.AccessType, Eco.Shared.SharedTypes.InteractionFlags, System.String[])'.
Source:System.Private.CoreLib
System.MissingMethodException: Method not found: 'Void Eco.Gameplay.Interactions.Interactors.InteractionAttribute..ctor(Eco.Shared.SharedTypes.InteractionTrigger, System.String, Eco.Shared.SharedTypes.InteractionModifier, System.String[], Single, Single, Eco.Shared.Items.ClientPredictedBlockAction, Int32, Boolean, Eco.Shared.Items.TriBool, System.String, Eco.Shared.Items.AccessType, Eco.Shared.SharedTypes.InteractionFlags, System.String[])'.
   at System.ModuleHandle.ResolveMethod(QCallModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, ReadOnlySpan`1 typeInstantiationContext, ReadOnlySpan`1 methodInstantiationContext)
   at System.ModuleHandle.ResolveMethodHandle(Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctorWithParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
   at Eco.Core.Controller.CoreAttributeExtensions.IsSyncToViewOrAutogen(MemberInfo member)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at Eco.Core.Controller.ControllerMarshalerService.BuildMethods(ControllerMarshaler marshaler)
   at Eco.Core.Controller.ControllerMarshalerService.BuildClassMarshaler(ControllerMarshaler marshaler)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Outer Exceptions:
One or more errors occurred. (Exception has been thrown by the target of an invocation.) (One or more errors occurred. (One or more errors occurred. (Method not found: 'Void Eco.Gameplay.Interactions.Interactors.InteractionAttribute..ctor(Eco.Shared.SharedTypes.InteractionTrigger, System.String, Eco.Shared.SharedTypes.InteractionModifier, System.String[], Single, Single, Eco.Shared.Items.ClientPredictedBlockAction, Int32, Boolean, Eco.Shared.Items.TriBool, System.String, Eco.Shared.Items.AccessType, Eco.Shared.SharedTypes.InteractionFlags, System.String[])'.)) (One or more errors occurred. (Method not found: 'Void Eco.Gameplay.Interactions.Interactors.InteractionAttribute..ctor(Eco.Shared.SharedTypes.InteractionTrigger, System.String, Eco.Shared.SharedTypes.InteractionModifier, System.String[], Single, Single, Eco.Shared.Items.ClientPredictedBlockAction, Int32, Boolean, Eco.Shared.Items.TriBool, System.String, Eco.Shared.Items.AccessType, Eco.Shared.SharedTypes.InteractionFlags, System.String[])'.)))
Exception has been thrown by the target of an invocation.
One or more errors occurred. (Method not found: 'Void Eco.Gameplay.Interactions.Interactors.InteractionAttribute..ctor(Eco.Shared.SharedTypes.InteractionTrigger, System.String, Eco.Shared.SharedTypes.InteractionModifier, System.String[], Single, Single, Eco.Shared.Items.ClientPredictedBlockAction, Int32, Boolean, Eco.Shared.Items.TriBool, System.String, Eco.Shared.Items.AccessType, Eco.Shared.SharedTypes.InteractionFlags, System.String[])'.)
: 1

**Server**
 - Eco Server Version [e.g. 9.6.2]
 - EM Framework Version [eg 3.3.1]

**Additional context**

**Comment by TheKye** [comment]
This has been fixed and a release pushed :)
